name: recordatorios_app
description: Aplicación de recordatorios con linterna y contador de pasos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  # Para Notificaciones (versión moderna)
  flutter_local_notifications: ^19.5.0

  # Dependencias de notificaciones (actualizadas)
  timezone: ^0.10.1

  # Para guardar historial (versión moderna)
  shared_preferences: ^2.2.3 # (Usamos una versión estable moderna)

  # Para Contador de Pasos (versión moderna que arregla el error)
  sensors_plus: ^7.0.0

  # Para Linterna (el paquete correcto y moderno)
  torch_light: ^1.1.0

  # Dependencia interna (actualizada)
  intl: ^0.20.2

  # NUEVO PAQUETE PARA PERMISOS
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true